name: Mobile Test Automation - Calendar App

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: mvn test -Dtest.suite=iOSRegression.xml