name: Mobile Test Automation - Calendar App

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: mvn test -Dtest.suite=iOSRegression.xml

      - name: Upload allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload screenshots folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots